if (process.env.NODE_ENV !== 'production') require('dotenv').config()

const { DBHOST, DBNAME, DBUSER, DBPASS, PORT, SENDGRID_API_KEY, JWTSECRET, CAPTCHAKEY, GCLOUD_STORAGE_BUCKET } = process.env

module.exports = { DBHOST, DBNAME, DBUSER, DBPASS, PORT, SENDGRID_API_KEY, JWTSECRET, CAPTCHAKEY, GCLOUD_STORAGE_BUCKET }